{
  "providers": ["nodejs"],
  "phases": {
    "setup": {
      "nixPkgs": ["nodejs-18_x", "playwright-driver", "chromium"]
    },
    "install": {
      "cmds": [
        "npm ci",
        "npx playwright install --with-deps chromium"
      ]
    },
    "build": {
      "cmds": ["npm run build"]
    }
  },
  "start": {
    "cmd": "npm start"
  }
}
